# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path
# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.

Rails.application.config.assets.precompile += %w( bootstrap/css/bootstrap.css )
Rails.application.config.assets.precompile += %w( bootstrap/css/bootstrap.min.css )
Rails.application.config.assets.precompile += %w( bootstrap/css/bootstrap-theme.css )
Rails.application.config.assets.precompile += %w( bootstrap/css/bootstrap-theme.min.css )
Rails.application.config.assets.precompile += %w( bootstrap/fonts/glyphicons-halflings-regular.eot )
Rails.application.config.assets.precompile += %w( bootstrap/fonts/glyphicons-halflings-regular.svg )
Rails.application.config.assets.precompile += %w( bootstrap/fonts/glyphicons-halflings-regular.ttf )
Rails.application.config.assets.precompile += %w( bootstrap/fonts/glyphicons-halflings-regular.woff )
Rails.application.config.assets.precompile += %w( bootstrap/fonts/glyphicons-halflings-regular.woff2 )
Rails.application.config.assets.precompile += %w( css/custom.css )
Rails.application.config.assets.precompile += %w( css/preloader.css )
Rails.application.config.assets.precompile += %w( css/style.css )
Rails.application.config.assets.precompile += %w( css/style-dark.css )
Rails.application.config.assets.precompile += %w( fonts/font-awesome/css/font-awesome.css )
Rails.application.config.assets.precompile += %w( fonts/font-awesome/css/font-awesome.min.css )
Rails.application.config.assets.precompile += %w( fonts/font-awesome/fonts/FontAwesome.otf )
Rails.application.config.assets.precompile += %w( fonts/font-awesome/fonts/fontawesome-webfont.eot )
Rails.application.config.assets.precompile += %w( fonts/font-awesome/fonts/fontawesome-webfont.svg )
Rails.application.config.assets.precompile += %w( fonts/font-awesome/fonts/fontawesome-webfont.ttf )
Rails.application.config.assets.precompile += %w( fonts/font-awesome/fonts/fontawesome-webfont.woff )
Rails.application.config.assets.precompile += %w( fonts/font-awesome/fonts/fontawesome-webfont.woff2 )
Rails.application.config.assets.precompile += %w( fonts/simple-line-icons/css/simple-line-icons.css )
Rails.application.config.assets.precompile += %w( fonts/simple-line-icons/fonts/Simple-Line-Icons.eot )
Rails.application.config.assets.precompile += %w( fonts/simple-line-iconsfonts/Simple-Line-Icons.svg )
Rails.application.config.assets.precompile += %w( fonts/simple-line-iconsfonts/Simple-Line-Icons.ttf )
Rails.application.config.assets.precompile += %w( fonts/simple-line-iconsfonts/Simple-Line-Icons.woff2 )
Rails.application.config.assets.precompile += %w( fonts/simple-line-iconsfonts/Simple-Line-Icons.woff2 )
Rails.application.config.assets.precompile += %w( magnific-popup/dist/magnific-popup.css )
Rails.application.config.assets.precompile += %w( slick/slick.css )
Rails.application.config.assets.precompile += %w( bootstrap/js/bootstrap.js )
Rails.application.config.assets.precompile += %w( bootstrap/js/bootstrap.min.js )
Rails.application.config.assets.precompile += %w( bootstrap/js/npm.js )
Rails.application.config.assets.precompile += %w( chartjs/chart.min.js )
Rails.application.config.assets.precompile += %w( countdown/dest/countdown.js )
Rails.application.config.assets.precompile += %w( countdown/dest/countdown.min.js )
Rails.application.config.assets.precompile += %w( countdown/dest/jquery.countdown.js )
Rails.application.config.assets.precompile += %w( countdown/dest/jquery.countdown.min.js )
Rails.application.config.assets.precompile += %w( custom-select/classie.js )
Rails.application.config.assets.precompile += %w( custom-select/selectFx.js )
Rails.application.config.assets.precompile += %w( easy-pie-chart/dist/easypiechart.js )
Rails.application.config.assets.precompile += %w( easy-pie-chart/dist/easypiechart.min.js )
Rails.application.config.assets.precompile += %w( easy-pie-chart/dist/jquery.easypiechart.js )
Rails.application.config.assets.precompile += %w( easy-pie-chart/dist/jquery.easypiechart.min.js )
Rails.application.config.assets.precompile += %w( gmap3/dist/gmap3.js )
Rails.application.config.assets.precompile += %w( gmap3/dist/gmap3.min.js )
Rails.application.config.assets.precompile += %w( imagesloaded/imagesloaded.js )
Rails.application.config.assets.precompile += %w( imagesloaded/imagesloaded.pkgd.js )
Rails.application.config.assets.precompile += %w( imagesloaded/imagesloaded.pkgd.min.js )
Rails.application.config.assets.precompile += %w( instafeed/instafeed.js )
Rails.application.config.assets.precompile += %w( isotope/dist/isotope.pkgd.js )
Rails.application.config.assets.precompile += %w( isotope/dist/isotope.pkgd.min.js )
Rails.application.config.assets.precompile += %w( jpreloader2/js/jpreloader.js )
Rails.application.config.assets.precompile += %w( jquery/jquery.js )
Rails.application.config.assets.precompile += %w( jquery/jquery.min.js )
Rails.application.config.assets.precompile += %w( jquery-duotone/jquery.duotone.js )
Rails.application.config.assets.precompile += %w( jquery-duotone/jquery.duotone.min.js )
Rails.application.config.assets.precompile += %w( js/core.js )
Rails.application.config.assets.precompile += %w( js/core-min.js )
Rails.application.config.assets.precompile += %w( js/custom.js )
Rails.application.config.assets.precompile += %w( js/init.js )
Rails.application.config.assets.precompile += %w( magnific-popup/dist/jquery.magnific-popup.js )
Rails.application.config.assets.precompile += %w( magnific-popup/dist/jquery.magnific-popup.min.js )
Rails.application.config.assets.precompile += %w( marquee/jquery.marquee.js )
Rails.application.config.assets.precompile += %w( marquee/jquery.marquee.min.js )
Rails.application.config.assets.precompile += %w( nouislider/nouislider.js )
Rails.application.config.assets.precompile += %w( nouislider/nouislider.min.js )
Rails.application.config.assets.precompile += %w( slick/slick.js )
Rails.application.config.assets.precompile += %w( slick/slick.min.js )
Rails.application.config.assets.precompile += %w( social-counters/social-counters-api.js )
Rails.application.config.assets.precompile += %w( social-counters/social-counters-api-min.js )
Rails.application.config.assets.precompile += %w( svg4everybody/svg4everybody.js )
Rails.application.config.assets.precompile += %w( svg4everybody/svg4everybody.min.js )
